export class Messages {
	public static get message() {
		return {
			SOMETHING_WRONG: 'Something went Wrong',
			RECORD_NOT_FOUND: 'Record not found',
			WALLET_NOT_CONNECTED: "Wallet not connected. Please connect your wallet first",
			PLEASE_CONNECT_WALLET: "Wallet not connected. Please connect your wallet to proceed."
		}
	}
	public static get CONST_MSG() {
		return {
			SLOGAN: "Your #1 Free Source of Likes, Subscribers, Tweets, Followers & Web Traffic",
			RESET: "Reset Password",
			FORGET: "Forgot password?",
			CREATE: "Create an Account",
			LOGIN: "Log In",
			RESET_PASSWORD: "Reset your password",
			CONFIRM_PASSWORD: "Confirm password and Password not matched",
			FORGET_PASSWORD: "Forgot your password?",
			GET_RESET_PASSWORD: "Get Reset Password Link",
			DONT_HAVE_ACCOUNT: "Don't have an account?",
			HAVE_ACCOUNT: "Have an account?",
			VERIFICATION_CODE: "Enter your verification code.",
			VERIFY_OTP: "Verify OTP",
			NO_DATA_FOUND: 'No Data Found',
			REFER_EARN: 'Refer And Earn',
			LEADERSHIP_BOARD: 'Leader Board',
			SIGN_UP: 'Sign Up',
			PASSWORD_CHANGE_SUCCESS: 'Password Changed Successfully',
			PASSWORD_RESET_LINK_VERIFY: 'Password reset link has been sent on your email',
			SOMETHING_WRONG: 'Something went Wrong',
			SOMETHING_UNUSUAL_HAPPEN: 'Something unusual happend, please try again!',
			DAILY_REWARD_LIMIT_EXCEED: 'Daily reward limit exhausted, please try again tomorrow',
			EARNED_SUCCESS: 'Earned Successfully',
			SUCCESS: 'Success',
			COPIED_TO_CLIPBOARD: 'Copied To Clipboard',
			WRONG_LINK_OR_TASK_NOT_PERFORM: 'Invalid post link or task not performed, please check and try again.',
			REQUEST_SUBMITTED: 'Request Submitted',
			TASK_VERIFIED_SUCCESS: 'Task Verified Successfully',
			SELECT_PROPER_IMG_FILE: 'Invalid file format. Please select a file in .jpeg, .jpg, or .png format',
			MAX_5MB_ALLOWED: 'File size exceeds the maximum limit of 5 MB. Please select a smaller file',
			UPLOAD_AGAIN: 'Error in uploading the attachment. Please try again',
			SERVER_ERROR: 'Server Error',
			ERROR: 'Error',
			UPLOADED_SUCCESSFULLY: 'Uploaded succesfully',
			REPORT_RAISED_SUCCESS: 'Report raised succesfully',
			PROMOTION_NAME_LIMIT_VALIDATION: 'Promotion name should not be greater than 80',
			NAME_ALREADY_EXIST: 'Name already exist!!',
			REWARD_EARNED: 'Earned Successfully',
			PROFILE_UPDATED_SUCCESSFULLY: 'Profile Updated Successfully',
			ERROR_IN_UPDATE_PROFILE_PIC: 'Error in updating Profile Picture',
			SOCIAL_CONNECTION_UPDATE_SUCCESS: 'Social connection updated successfully',
			ERROR_UPDATING_SOCIAL_CONNECTION: 'There was an error in updating your social connection. Please try again later',
			DETAILS_ADDED_SUCCESS: 'Details Added Successfully',
			COULD_NOT_COPY_TEXT: 'Could not copy text',
			TRY_AGAIN: 'Please try again!',
			TDX_LAUNCHPAD: 'TDX Launchpad | Dashboard',
			COMPLETE_KYC:'Complete your KYC first.',
			INPUT_BLANK:'Input blank!',
			BALANCE_TOO_LOW:'Wallet balance too low!',
			NOT_SUFFICIENT_FUND:'Not sufficient fund',
			SUCCESSFULLY_PURCHASED:'Successfully Purchased',
			UPDATE_WALLET:'Update Wallet',
			WALLET:'Wallet',
			PURCHASE_LIMIT_EXCEED:'Your purchase limit exceeded.',
			SUCCESSFUL_PAYMENT:'Thank you! This transaction will be completed on Successful Payment',
			INVOICE_VALID_FOR_1HOUR:'This invoice is saved in "Transactions" and is valid for 1 hour',
			INVOICE_CANCELLED_AUTOMATICALLY:'This Invoice will be cancelled automatically',
			REQUEST_SUBMITTED_SUCCESSFULLY:'Request Submitted Successfully',
			SOME_ERROR_OCCURED:'Some error occured',
			SOMETHING_WENT_WRONG:'Something went wrong',
			REFER_LINK_AVAILABLE:'Refer Link Available',
			REFERRAL_LINK_NOT_AVAILABLE:'Refer Link not Available',
			REFERRAL_LINK_UPDATED:'User referral link updated successfully.',
			CMAPAIGN_NAME_REQUIRED:'Campaign name is required',
			CAMPAIGN_SHOULD_NOT_GREATER_THAN_40:'Campaign name should not be greater than 40',
			PLEASE_SELECT_IMAGE:'Please select an image',
			FACING_SOME_PROBLEM:'Facing some problem',
			EMAIL_PREFRENCE_UPDATED:'Email preferences updated',
			PLAESE_ENABLE_YOUR_WALLET:'Please enable your wallet to proceed.',
			PLEASE_SELECT_PAYMENT_METHOD:'Please select token',
			MINIMUM_AMOUNT_WIDHRAWAL:'Minimum amount for withdrawal',
			PLEASE_TRY_AGAIN:'Please try again!',
			WALLET_CREATED_SUCCESSFULLY:'Wallet created successfully',
			COUPON_REDEEMED_SUCCESSFULLY:'Coupon redeemed successfully',
			COUPON:'Coupon',
			COUPON_CANNOT_BE_BLANK:'Coupon code can not be blank!',
			SELECT_COIN:'Please select coin to make payment',
			TRANSACTION_SUCCESSFULL:'Thank you! This transaction will be completed on Successful Payment',
			INVOICE_SAVED:'This invoice is saved in "My Deposit" inside Wallet and is valid for 1 hour',
			ENTER_AMOUNT:'Please enter amount',
			MAX_LIMIT:'Max limit exceeded.',
			INSUFFICIENT_FUND: 'Insufficient Fund',
			PAYMODE_BLANK: 'Paymode blank',
			PLEASE_VERIFY_CAPTCHA: 'Please verify captcha',
			PLEASE_ACCEPT_TERMS_CONDITIOND: 'Please accept terms & conditions',
			ACCOUNT_ALREADY_VERIFIED: 'Account is already verified',
			YOU_HAVE_ALREADY_CREATED_ACCOUNT_LOGIN_TO_CONTINUE: 'You have already created account. Please login to continue',
			PLEASE_CHECK_YOUR_EMAIL: 'Please check your email',
			CONFIRM_PASSWORD_MISMATCH: 'Confirm password mismatch',
			PASSWORD: 'Password',
			PLEASE_CHECK_EMAIL_FOR_VERIFICATION_LINK: 'Please check your email for verification link',
			VERIFICATION_LINK: 'Verification Link',
			NO_ACCESS_ALLOWED: 'No Access Allowed',
			PLEASE_ENTER_OTP: 'Please enter OTP',
			VERIFICATION_SUCCESSFULL: 'Verification Successful',
			TOKEN: 'Token',
			DEFAULT: 'DEFAULT',
			APPROVED: 'APPROVED',
			DECLINED: 'DECLINED',
			ACCEPTED: 'ACCEPTED',
			FAILED: 'FAILED',
			INVALID:'INVALID',
			DEPOSIT: 'DEPOSIT',
			PURCHASE: 'PURCHASE',
			REJECTED: 'REJECTED',
			RED: 'RED',
			RETRY: 'RETRY',
			TRUE: "true",
			FIRST_NAME: 'firstName',
			USER: 'user',
			PLEASE_ANSWER_ALL_QUESTIONS: 'Please answer all questions',
			SOCIAL_ADDED_SUCCESSFULLY: 'Your social account added successfully ',
			FAILED_TOCONNECT_SOCIAL: 'Failed to update social connection. Please try again later.',
			PASSWORD_CHANGED_SUCCESS: 'Password Changed Successfully',
			PURCHASED_SUCCESSFULLY: 'Purchased Succesfully',
			NO_CLAIMING_SCHEDULE_FOUND: 'No Claiming Schedules Found !!',
			SOME_ERROR_OCCUR: 'Some error occur',
			PERFORM_PRIMARY_TASK_FIRST: 'Please Perform Primary Task First'
		}
	}
}
